/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class FollowSchema extends BaseModel {
  static $columns = ['createdAt', 'followerId', 'followingId', 'id', 'updatedAt'] as const
  $columns = FollowSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare followerId: number | null
  @column()
  declare followingId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LikeSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'tweetId', 'updatedAt', 'userId'] as const
  $columns = LikeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tweetId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class TweetSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'id', 'mediaType', 'mediaUrl', 'updatedAt', 'userId'] as const
  $columns = TweetSchema.$columns
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mediaType: string | null
  @column()
  declare mediaUrl: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'bannerUrl', 'bio', 'createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column()
  declare bannerUrl: string | null
  @column()
  declare bio: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}
